INSERT INTO backpacks(mark) VALUES('Military10XL');
INSERT INTO backpacks(mark) VALUES('NikePRO');
INSERT INTO backpacks(mark) VALUES('CasualUK');
INSERT INTO backpacks(mark) VALUES('Adidas60');
INSERT INTO notepads(title, backpack_id) VALUES('History', 1);
INSERT INTO notepads(title, backpack_id) VALUES('Maths', 1);
INSERT INTO notepads(title, backpack_id) VALUES('Biology', 2);
INSERT INTO notepads(title, backpack_id) VALUES('Physics', 2);
INSERT INTO notepads(title, backpack_id) VALUES('Chemistry', 2);
INSERT INTO notepads(title, backpack_id) VALUES('Chemistry', 3);
INSERT INTO notepads(title, backpack_id) VALUES('Music', 4);
INSERT INTO notepads(title, backpack_id) VALUES('English', 4);
INSERT INTO notes(number, notepad_id) VALUES(22, 1);
INSERT INTO notes(number, notepad_id) VALUES(11, 3);
INSERT INTO notes(number, notepad_id) VALUES(32, 5);
INSERT INTO notes(number, notepad_id) VALUES(45, 4);
INSERT INTO notes(number, notepad_id) VALUES(100, 2);
INSERT INTO notes(number, notepad_id) VALUES(101, 2);
INSERT INTO notes(number, notepad_id) VALUES(102, 2);
INSERT INTO students(group_number, name, surname, backpack_id) VALUES(1, 'Steve', 'Jobs', 1);
INSERT INTO students(group_number, name, surname, backpack_id) VALUES(1, 'Bill', 'Gates', 2);
INSERT INTO students(group_number, name, surname, backpack_id) VALUES(1, 'Alan', 'Turing', 3);
INSERT INTO students(group_number, name, surname, backpack_id) VALUES(1, 'Linus', 'Torvalds', 4);
INSERT INTO professors(name, surname, title) VALUES('Mike', 'Dawes', 'PhD');
INSERT INTO professors(name, surname, title) VALUES('Ian', 'Stewart', 'Professor');
INSERT INTO students_professor_set(student_set_id, professor_set_id) VALUES(1,1);
INSERT INTO students_professor_set(student_set_id, professor_set_id) VALUES(2,1);
INSERT INTO students_professor_set(student_set_id, professor_set_id) VALUES(3,1);
INSERT INTO students_professor_set(student_set_id, professor_set_id) VALUES(4,1);
INSERT INTO students_professor_set(student_set_id, professor_set_id) VALUES(1,2);
INSERT INTO students_professor_set(student_set_id, professor_set_id) VALUES(2,2);
INSERT INTO students_professor_set(student_set_id, professor_set_id) VALUES(3,2);
INSERT INTO students_professor_set(student_set_id, professor_set_id) VALUES(4,2);
INSERT INTO rooms(room_number, professor_id) VALUES (332, 1);
INSERT INTO rooms(room_number, professor_id) VALUES (405, 2);
INSERT INTO cleaners(name, surname) VALUES('Stan', 'Gold');
INSERT INTO cleaners(name, surname) VALUES('Brad', 'Brown');
INSERT INTO cleaners(name, surname) VALUES('Olivia', 'Wallace');
INSERT INTO cleaners_room_set(cleaner_set_id, room_set_id) VALUES(1,1);
INSERT INTO cleaners_room_set(cleaner_set_id, room_set_id) VALUES(2,1);
INSERT INTO cleaners_room_set(cleaner_set_id, room_set_id) VALUES(3,2);

